# Generated by Django 3.2.7 on 2021-09-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Таск', 'verbose_name_plural': 'Таски'},
        ),
        migrations.AlterField(
            model_name='task',
            name='full_description',
            field=models.TextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='short_description',
            field=models.TextField(verbose_name='Короткое описание'),
        ),
    ]
