# Generated by Django 3.2.7 on 2021-09-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210927_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='payment_parts',
            field=models.CharField(choices=[('1/2', '50%'), ('1/3', '33%'), ('1/4', '25%'), ('Full', '100%')], default='1/2', max_length=50, verbose_name='Части оплаты'),
        ),
    ]
