# Generated by Django 3.2.7 on 2021-11-24 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_payment_parts'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_mdl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.IntegerField(verbose_name='Сумма')),
                ('payment_date', models.DateField(verbose_name='Дата поступления оплаты')),
                ('task_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task', verbose_name='Таск')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
    ]
