# Generated by Django 3.2.7 on 2021-11-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_payment_mdl'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_mdl',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено?'),
        ),
    ]
