# Generated by Django 3.2.7 on 2021-11-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_payment_mdl_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_mdl',
            name='payment_id',
            field=models.TextField(default=1, verbose_name='Идентификатор оплаты'),
            preserve_default=False,
        ),
    ]
